/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRealtimeRouteImport } from './routes/api/realtime'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as ApiStorageSplatRouteImport } from './routes/api/storage/$'
import { Route as AuthenticatedAppScanRouteImport } from './routes/_authenticated/app/scan'
import { Route as AuthenticatedAppOtcRouteImport } from './routes/_authenticated/app/otc'
import { Route as ApiAuthGoogleIndexRouteImport } from './routes/api/auth/google/index'
import { Route as AuthenticatedAppReservationsIndexRouteImport } from './routes/_authenticated/app/reservations/index'
import { Route as AuthenticatedAppPrescriptionsIndexRouteImport } from './routes/_authenticated/app/prescriptions/index'
import { Route as AuthenticatedAppPraticienIndexRouteImport } from './routes/_authenticated/app/praticien/index'
import { Route as AuthenticatedAppPharmacyIndexRouteImport } from './routes/_authenticated/app/pharmacy/index'
import { Route as AuthenticatedAppHealthIndexRouteImport } from './routes/_authenticated/app/health/index'
import { Route as AuthenticatedAppCourierIndexRouteImport } from './routes/_authenticated/app/courier/index'
import { Route as AuthenticatedAppAppointmentsIndexRouteImport } from './routes/_authenticated/app/appointments/index'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app/admin/index'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'
import { Route as AuthenticatedAppPharmacyOnboardingRouteImport } from './routes/_authenticated/app/pharmacy/onboarding'
import { Route as AuthenticatedAppCourierOnboardingRouteImport } from './routes/_authenticated/app/courier/onboarding'
import { Route as AuthenticatedAppAdminWhatsappRouteImport } from './routes/_authenticated/app/admin/whatsapp'
import { Route as AuthenticatedAppAdminReviewsRouteImport } from './routes/_authenticated/app/admin/reviews'
import { Route as AuthenticatedAppAdminPractitionersRouteImport } from './routes/_authenticated/app/admin/practitioners'
import { Route as AuthenticatedAppAdminPharmaciesRouteImport } from './routes/_authenticated/app/admin/pharmacies'
import { Route as AuthenticatedAppAdminPatientsRouteImport } from './routes/_authenticated/app/admin/patients'
import { Route as AuthenticatedAppAdminNeighborhoodsRouteImport } from './routes/_authenticated/app/admin/neighborhoods'
import { Route as AuthenticatedAppAdminInventoryRouteImport } from './routes/_authenticated/app/admin/inventory'
import { Route as AuthenticatedAppAdminFeedbackRouteImport } from './routes/_authenticated/app/admin/feedback'
import { Route as AuthenticatedAppAdminCouriersRouteImport } from './routes/_authenticated/app/admin/couriers'
import { Route as AuthenticatedAppAdminAppointmentsRouteImport } from './routes/_authenticated/app/admin/appointments'
import { Route as AuthenticatedAppReservationsIdIndexRouteImport } from './routes/_authenticated/app/reservations/$id/index'
import { Route as AuthenticatedAppPrescriptionsIdIndexRouteImport } from './routes/_authenticated/app/prescriptions/$id/index'
import { Route as AuthenticatedAppReservationsIdTrackRouteImport } from './routes/_authenticated/app/reservations/$id/track'
import { Route as AuthenticatedAppReservationsIdCheckoutRouteImport } from './routes/_authenticated/app/reservations/$id/checkout'
import { Route as AuthenticatedAppPrescriptionsIdPharmaciesRouteImport } from './routes/_authenticated/app/prescriptions/$id/pharmacies'
import { Route as AuthenticatedAppPraticienRdvIdRouteImport } from './routes/_authenticated/app/praticien/rdv/$id'
import { Route as AuthenticatedAppPharmacyPharmacyIdReservationsRouteImport } from './routes/_authenticated/app/pharmacy/$pharmacyId/reservations'
import { Route as AuthenticatedAppPharmacyPharmacyIdInventoryRouteImport } from './routes/_authenticated/app/pharmacy/$pharmacyId/inventory'
import { Route as AuthenticatedAppCourierDeliveriesIdRouteImport } from './routes/_authenticated/app/courier/deliveries/$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageSplatRoute = ApiStorageSplatRouteImport.update({
  id: '/api/storage/$',
  path: '/api/storage/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppScanRoute = AuthenticatedAppScanRouteImport.update({
  id: '/app/scan',
  path: '/app/scan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppOtcRoute = AuthenticatedAppOtcRouteImport.update({
  id: '/app/otc',
  path: '/app/otc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthGoogleIndexRoute = ApiAuthGoogleIndexRouteImport.update({
  id: '/api/auth/google/',
  path: '/api/auth/google/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppReservationsIndexRoute =
  AuthenticatedAppReservationsIndexRouteImport.update({
    id: '/app/reservations/',
    path: '/app/reservations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppPrescriptionsIndexRoute =
  AuthenticatedAppPrescriptionsIndexRouteImport.update({
    id: '/app/prescriptions/',
    path: '/app/prescriptions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppPraticienIndexRoute =
  AuthenticatedAppPraticienIndexRouteImport.update({
    id: '/app/praticien/',
    path: '/app/praticien/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppPharmacyIndexRoute =
  AuthenticatedAppPharmacyIndexRouteImport.update({
    id: '/app/pharmacy/',
    path: '/app/pharmacy/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppHealthIndexRoute =
  AuthenticatedAppHealthIndexRouteImport.update({
    id: '/app/health/',
    path: '/app/health/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppCourierIndexRoute =
  AuthenticatedAppCourierIndexRouteImport.update({
    id: '/app/courier/',
    path: '/app/courier/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAppointmentsIndexRoute =
  AuthenticatedAppAppointmentsIndexRouteImport.update({
    id: '/app/appointments/',
    path: '/app/appointments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/app/admin/',
    path: '/app/admin/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppPharmacyOnboardingRoute =
  AuthenticatedAppPharmacyOnboardingRouteImport.update({
    id: '/app/pharmacy/onboarding',
    path: '/app/pharmacy/onboarding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppCourierOnboardingRoute =
  AuthenticatedAppCourierOnboardingRouteImport.update({
    id: '/app/courier/onboarding',
    path: '/app/courier/onboarding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminWhatsappRoute =
  AuthenticatedAppAdminWhatsappRouteImport.update({
    id: '/app/admin/whatsapp',
    path: '/app/admin/whatsapp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminReviewsRoute =
  AuthenticatedAppAdminReviewsRouteImport.update({
    id: '/app/admin/reviews',
    path: '/app/admin/reviews',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminPractitionersRoute =
  AuthenticatedAppAdminPractitionersRouteImport.update({
    id: '/app/admin/practitioners',
    path: '/app/admin/practitioners',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminPharmaciesRoute =
  AuthenticatedAppAdminPharmaciesRouteImport.update({
    id: '/app/admin/pharmacies',
    path: '/app/admin/pharmacies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminPatientsRoute =
  AuthenticatedAppAdminPatientsRouteImport.update({
    id: '/app/admin/patients',
    path: '/app/admin/patients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminNeighborhoodsRoute =
  AuthenticatedAppAdminNeighborhoodsRouteImport.update({
    id: '/app/admin/neighborhoods',
    path: '/app/admin/neighborhoods',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminInventoryRoute =
  AuthenticatedAppAdminInventoryRouteImport.update({
    id: '/app/admin/inventory',
    path: '/app/admin/inventory',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminFeedbackRoute =
  AuthenticatedAppAdminFeedbackRouteImport.update({
    id: '/app/admin/feedback',
    path: '/app/admin/feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminCouriersRoute =
  AuthenticatedAppAdminCouriersRouteImport.update({
    id: '/app/admin/couriers',
    path: '/app/admin/couriers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminAppointmentsRoute =
  AuthenticatedAppAdminAppointmentsRouteImport.update({
    id: '/app/admin/appointments',
    path: '/app/admin/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppReservationsIdIndexRoute =
  AuthenticatedAppReservationsIdIndexRouteImport.update({
    id: '/app/reservations/$id/',
    path: '/app/reservations/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppPrescriptionsIdIndexRoute =
  AuthenticatedAppPrescriptionsIdIndexRouteImport.update({
    id: '/app/prescriptions/$id/',
    path: '/app/prescriptions/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppReservationsIdTrackRoute =
  AuthenticatedAppReservationsIdTrackRouteImport.update({
    id: '/app/reservations/$id/track',
    path: '/app/reservations/$id/track',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppReservationsIdCheckoutRoute =
  AuthenticatedAppReservationsIdCheckoutRouteImport.update({
    id: '/app/reservations/$id/checkout',
    path: '/app/reservations/$id/checkout',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppPrescriptionsIdPharmaciesRoute =
  AuthenticatedAppPrescriptionsIdPharmaciesRouteImport.update({
    id: '/app/prescriptions/$id/pharmacies',
    path: '/app/prescriptions/$id/pharmacies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppPraticienRdvIdRoute =
  AuthenticatedAppPraticienRdvIdRouteImport.update({
    id: '/app/praticien/rdv/$id',
    path: '/app/praticien/rdv/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppPharmacyPharmacyIdReservationsRoute =
  AuthenticatedAppPharmacyPharmacyIdReservationsRouteImport.update({
    id: '/app/pharmacy/$pharmacyId/reservations',
    path: '/app/pharmacy/$pharmacyId/reservations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppPharmacyPharmacyIdInventoryRoute =
  AuthenticatedAppPharmacyPharmacyIdInventoryRouteImport.update({
    id: '/app/pharmacy/$pharmacyId/inventory',
    path: '/app/pharmacy/$pharmacyId/inventory',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppCourierDeliveriesIdRoute =
  AuthenticatedAppCourierDeliveriesIdRouteImport.update({
    id: '/app/courier/deliveries/$id',
    path: '/app/courier/deliveries/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/feedback': typeof FeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/app/otc': typeof AuthenticatedAppOtcRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/appointments': typeof AuthenticatedAppAdminAppointmentsRoute
  '/app/admin/couriers': typeof AuthenticatedAppAdminCouriersRoute
  '/app/admin/feedback': typeof AuthenticatedAppAdminFeedbackRoute
  '/app/admin/inventory': typeof AuthenticatedAppAdminInventoryRoute
  '/app/admin/neighborhoods': typeof AuthenticatedAppAdminNeighborhoodsRoute
  '/app/admin/patients': typeof AuthenticatedAppAdminPatientsRoute
  '/app/admin/pharmacies': typeof AuthenticatedAppAdminPharmaciesRoute
  '/app/admin/practitioners': typeof AuthenticatedAppAdminPractitionersRoute
  '/app/admin/reviews': typeof AuthenticatedAppAdminReviewsRoute
  '/app/admin/whatsapp': typeof AuthenticatedAppAdminWhatsappRoute
  '/app/courier/onboarding': typeof AuthenticatedAppCourierOnboardingRoute
  '/app/pharmacy/onboarding': typeof AuthenticatedAppPharmacyOnboardingRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/appointments/': typeof AuthenticatedAppAppointmentsIndexRoute
  '/app/courier/': typeof AuthenticatedAppCourierIndexRoute
  '/app/health/': typeof AuthenticatedAppHealthIndexRoute
  '/app/pharmacy/': typeof AuthenticatedAppPharmacyIndexRoute
  '/app/praticien/': typeof AuthenticatedAppPraticienIndexRoute
  '/app/prescriptions/': typeof AuthenticatedAppPrescriptionsIndexRoute
  '/app/reservations/': typeof AuthenticatedAppReservationsIndexRoute
  '/api/auth/google/': typeof ApiAuthGoogleIndexRoute
  '/app/courier/deliveries/$id': typeof AuthenticatedAppCourierDeliveriesIdRoute
  '/app/pharmacy/$pharmacyId/inventory': typeof AuthenticatedAppPharmacyPharmacyIdInventoryRoute
  '/app/pharmacy/$pharmacyId/reservations': typeof AuthenticatedAppPharmacyPharmacyIdReservationsRoute
  '/app/praticien/rdv/$id': typeof AuthenticatedAppPraticienRdvIdRoute
  '/app/prescriptions/$id/pharmacies': typeof AuthenticatedAppPrescriptionsIdPharmaciesRoute
  '/app/reservations/$id/checkout': typeof AuthenticatedAppReservationsIdCheckoutRoute
  '/app/reservations/$id/track': typeof AuthenticatedAppReservationsIdTrackRoute
  '/app/prescriptions/$id/': typeof AuthenticatedAppPrescriptionsIdIndexRoute
  '/app/reservations/$id/': typeof AuthenticatedAppReservationsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/feedback': typeof FeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/app/otc': typeof AuthenticatedAppOtcRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/appointments': typeof AuthenticatedAppAdminAppointmentsRoute
  '/app/admin/couriers': typeof AuthenticatedAppAdminCouriersRoute
  '/app/admin/feedback': typeof AuthenticatedAppAdminFeedbackRoute
  '/app/admin/inventory': typeof AuthenticatedAppAdminInventoryRoute
  '/app/admin/neighborhoods': typeof AuthenticatedAppAdminNeighborhoodsRoute
  '/app/admin/patients': typeof AuthenticatedAppAdminPatientsRoute
  '/app/admin/pharmacies': typeof AuthenticatedAppAdminPharmaciesRoute
  '/app/admin/practitioners': typeof AuthenticatedAppAdminPractitionersRoute
  '/app/admin/reviews': typeof AuthenticatedAppAdminReviewsRoute
  '/app/admin/whatsapp': typeof AuthenticatedAppAdminWhatsappRoute
  '/app/courier/onboarding': typeof AuthenticatedAppCourierOnboardingRoute
  '/app/pharmacy/onboarding': typeof AuthenticatedAppPharmacyOnboardingRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/appointments': typeof AuthenticatedAppAppointmentsIndexRoute
  '/app/courier': typeof AuthenticatedAppCourierIndexRoute
  '/app/health': typeof AuthenticatedAppHealthIndexRoute
  '/app/pharmacy': typeof AuthenticatedAppPharmacyIndexRoute
  '/app/praticien': typeof AuthenticatedAppPraticienIndexRoute
  '/app/prescriptions': typeof AuthenticatedAppPrescriptionsIndexRoute
  '/app/reservations': typeof AuthenticatedAppReservationsIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleIndexRoute
  '/app/courier/deliveries/$id': typeof AuthenticatedAppCourierDeliveriesIdRoute
  '/app/pharmacy/$pharmacyId/inventory': typeof AuthenticatedAppPharmacyPharmacyIdInventoryRoute
  '/app/pharmacy/$pharmacyId/reservations': typeof AuthenticatedAppPharmacyPharmacyIdReservationsRoute
  '/app/praticien/rdv/$id': typeof AuthenticatedAppPraticienRdvIdRoute
  '/app/prescriptions/$id/pharmacies': typeof AuthenticatedAppPrescriptionsIdPharmaciesRoute
  '/app/reservations/$id/checkout': typeof AuthenticatedAppReservationsIdCheckoutRoute
  '/app/reservations/$id/track': typeof AuthenticatedAppReservationsIdTrackRoute
  '/app/prescriptions/$id': typeof AuthenticatedAppPrescriptionsIdIndexRoute
  '/app/reservations/$id': typeof AuthenticatedAppReservationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/feedback': typeof FeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/_authenticated/app/otc': typeof AuthenticatedAppOtcRoute
  '/_authenticated/app/scan': typeof AuthenticatedAppScanRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/appointments': typeof AuthenticatedAppAdminAppointmentsRoute
  '/_authenticated/app/admin/couriers': typeof AuthenticatedAppAdminCouriersRoute
  '/_authenticated/app/admin/feedback': typeof AuthenticatedAppAdminFeedbackRoute
  '/_authenticated/app/admin/inventory': typeof AuthenticatedAppAdminInventoryRoute
  '/_authenticated/app/admin/neighborhoods': typeof AuthenticatedAppAdminNeighborhoodsRoute
  '/_authenticated/app/admin/patients': typeof AuthenticatedAppAdminPatientsRoute
  '/_authenticated/app/admin/pharmacies': typeof AuthenticatedAppAdminPharmaciesRoute
  '/_authenticated/app/admin/practitioners': typeof AuthenticatedAppAdminPractitionersRoute
  '/_authenticated/app/admin/reviews': typeof AuthenticatedAppAdminReviewsRoute
  '/_authenticated/app/admin/whatsapp': typeof AuthenticatedAppAdminWhatsappRoute
  '/_authenticated/app/courier/onboarding': typeof AuthenticatedAppCourierOnboardingRoute
  '/_authenticated/app/pharmacy/onboarding': typeof AuthenticatedAppPharmacyOnboardingRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/appointments/': typeof AuthenticatedAppAppointmentsIndexRoute
  '/_authenticated/app/courier/': typeof AuthenticatedAppCourierIndexRoute
  '/_authenticated/app/health/': typeof AuthenticatedAppHealthIndexRoute
  '/_authenticated/app/pharmacy/': typeof AuthenticatedAppPharmacyIndexRoute
  '/_authenticated/app/praticien/': typeof AuthenticatedAppPraticienIndexRoute
  '/_authenticated/app/prescriptions/': typeof AuthenticatedAppPrescriptionsIndexRoute
  '/_authenticated/app/reservations/': typeof AuthenticatedAppReservationsIndexRoute
  '/api/auth/google/': typeof ApiAuthGoogleIndexRoute
  '/_authenticated/app/courier/deliveries/$id': typeof AuthenticatedAppCourierDeliveriesIdRoute
  '/_authenticated/app/pharmacy/$pharmacyId/inventory': typeof AuthenticatedAppPharmacyPharmacyIdInventoryRoute
  '/_authenticated/app/pharmacy/$pharmacyId/reservations': typeof AuthenticatedAppPharmacyPharmacyIdReservationsRoute
  '/_authenticated/app/praticien/rdv/$id': typeof AuthenticatedAppPraticienRdvIdRoute
  '/_authenticated/app/prescriptions/$id/pharmacies': typeof AuthenticatedAppPrescriptionsIdPharmaciesRoute
  '/_authenticated/app/reservations/$id/checkout': typeof AuthenticatedAppReservationsIdCheckoutRoute
  '/_authenticated/app/reservations/$id/track': typeof AuthenticatedAppReservationsIdTrackRoute
  '/_authenticated/app/prescriptions/$id/': typeof AuthenticatedAppPrescriptionsIdIndexRoute
  '/_authenticated/app/reservations/$id/': typeof AuthenticatedAppReservationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/feedback'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api/realtime'
    | '/app/otc'
    | '/app/scan'
    | '/api/storage/$'
    | '/api/storage/upload'
    | '/app/'
    | '/app/admin/appointments'
    | '/app/admin/couriers'
    | '/app/admin/feedback'
    | '/app/admin/inventory'
    | '/app/admin/neighborhoods'
    | '/app/admin/patients'
    | '/app/admin/pharmacies'
    | '/app/admin/practitioners'
    | '/app/admin/reviews'
    | '/app/admin/whatsapp'
    | '/app/courier/onboarding'
    | '/app/pharmacy/onboarding'
    | '/api/auth/google/callback'
    | '/api/public/whatsapp/webhook'
    | '/app/admin/'
    | '/app/appointments/'
    | '/app/courier/'
    | '/app/health/'
    | '/app/pharmacy/'
    | '/app/praticien/'
    | '/app/prescriptions/'
    | '/app/reservations/'
    | '/api/auth/google/'
    | '/app/courier/deliveries/$id'
    | '/app/pharmacy/$pharmacyId/inventory'
    | '/app/pharmacy/$pharmacyId/reservations'
    | '/app/praticien/rdv/$id'
    | '/app/prescriptions/$id/pharmacies'
    | '/app/reservations/$id/checkout'
    | '/app/reservations/$id/track'
    | '/app/prescriptions/$id/'
    | '/app/reservations/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/feedback'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api/realtime'
    | '/app/otc'
    | '/app/scan'
    | '/api/storage/$'
    | '/api/storage/upload'
    | '/app'
    | '/app/admin/appointments'
    | '/app/admin/couriers'
    | '/app/admin/feedback'
    | '/app/admin/inventory'
    | '/app/admin/neighborhoods'
    | '/app/admin/patients'
    | '/app/admin/pharmacies'
    | '/app/admin/practitioners'
    | '/app/admin/reviews'
    | '/app/admin/whatsapp'
    | '/app/courier/onboarding'
    | '/app/pharmacy/onboarding'
    | '/api/auth/google/callback'
    | '/api/public/whatsapp/webhook'
    | '/app/admin'
    | '/app/appointments'
    | '/app/courier'
    | '/app/health'
    | '/app/pharmacy'
    | '/app/praticien'
    | '/app/prescriptions'
    | '/app/reservations'
    | '/api/auth/google'
    | '/app/courier/deliveries/$id'
    | '/app/pharmacy/$pharmacyId/inventory'
    | '/app/pharmacy/$pharmacyId/reservations'
    | '/app/praticien/rdv/$id'
    | '/app/prescriptions/$id/pharmacies'
    | '/app/reservations/$id/checkout'
    | '/app/reservations/$id/track'
    | '/app/prescriptions/$id'
    | '/app/reservations/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-callback'
    | '/feedback'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api/realtime'
    | '/_authenticated/app/otc'
    | '/_authenticated/app/scan'
    | '/api/storage/$'
    | '/api/storage/upload'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/appointments'
    | '/_authenticated/app/admin/couriers'
    | '/_authenticated/app/admin/feedback'
    | '/_authenticated/app/admin/inventory'
    | '/_authenticated/app/admin/neighborhoods'
    | '/_authenticated/app/admin/patients'
    | '/_authenticated/app/admin/pharmacies'
    | '/_authenticated/app/admin/practitioners'
    | '/_authenticated/app/admin/reviews'
    | '/_authenticated/app/admin/whatsapp'
    | '/_authenticated/app/courier/onboarding'
    | '/_authenticated/app/pharmacy/onboarding'
    | '/api/auth/google/callback'
    | '/api/public/whatsapp/webhook'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/appointments/'
    | '/_authenticated/app/courier/'
    | '/_authenticated/app/health/'
    | '/_authenticated/app/pharmacy/'
    | '/_authenticated/app/praticien/'
    | '/_authenticated/app/prescriptions/'
    | '/_authenticated/app/reservations/'
    | '/api/auth/google/'
    | '/_authenticated/app/courier/deliveries/$id'
    | '/_authenticated/app/pharmacy/$pharmacyId/inventory'
    | '/_authenticated/app/pharmacy/$pharmacyId/reservations'
    | '/_authenticated/app/praticien/rdv/$id'
    | '/_authenticated/app/prescriptions/$id/pharmacies'
    | '/_authenticated/app/reservations/$id/checkout'
    | '/_authenticated/app/reservations/$id/track'
    | '/_authenticated/app/prescriptions/$id/'
    | '/_authenticated/app/reservations/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  FeedbackRoute: typeof FeedbackRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  ApiStorageSplatRoute: typeof ApiStorageSplatRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiAuthGoogleIndexRoute: typeof ApiAuthGoogleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/$': {
      id: '/api/storage/$'
      path: '/api/storage/$'
      fullPath: '/api/storage/$'
      preLoaderRoute: typeof ApiStorageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/scan': {
      id: '/_authenticated/app/scan'
      path: '/app/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AuthenticatedAppScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/otc': {
      id: '/_authenticated/app/otc'
      path: '/app/otc'
      fullPath: '/app/otc'
      preLoaderRoute: typeof AuthenticatedAppOtcRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/google/': {
      id: '/api/auth/google/'
      path: '/api/auth/google'
      fullPath: '/api/auth/google/'
      preLoaderRoute: typeof ApiAuthGoogleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/reservations/': {
      id: '/_authenticated/app/reservations/'
      path: '/app/reservations'
      fullPath: '/app/reservations/'
      preLoaderRoute: typeof AuthenticatedAppReservationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/prescriptions/': {
      id: '/_authenticated/app/prescriptions/'
      path: '/app/prescriptions'
      fullPath: '/app/prescriptions/'
      preLoaderRoute: typeof AuthenticatedAppPrescriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/praticien/': {
      id: '/_authenticated/app/praticien/'
      path: '/app/praticien'
      fullPath: '/app/praticien/'
      preLoaderRoute: typeof AuthenticatedAppPraticienIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/pharmacy/': {
      id: '/_authenticated/app/pharmacy/'
      path: '/app/pharmacy'
      fullPath: '/app/pharmacy/'
      preLoaderRoute: typeof AuthenticatedAppPharmacyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/health/': {
      id: '/_authenticated/app/health/'
      path: '/app/health'
      fullPath: '/app/health/'
      preLoaderRoute: typeof AuthenticatedAppHealthIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/courier/': {
      id: '/_authenticated/app/courier/'
      path: '/app/courier'
      fullPath: '/app/courier/'
      preLoaderRoute: typeof AuthenticatedAppCourierIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/appointments/': {
      id: '/_authenticated/app/appointments/'
      path: '/app/appointments'
      fullPath: '/app/appointments/'
      preLoaderRoute: typeof AuthenticatedAppAppointmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/app/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/pharmacy/onboarding': {
      id: '/_authenticated/app/pharmacy/onboarding'
      path: '/app/pharmacy/onboarding'
      fullPath: '/app/pharmacy/onboarding'
      preLoaderRoute: typeof AuthenticatedAppPharmacyOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/courier/onboarding': {
      id: '/_authenticated/app/courier/onboarding'
      path: '/app/courier/onboarding'
      fullPath: '/app/courier/onboarding'
      preLoaderRoute: typeof AuthenticatedAppCourierOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/whatsapp': {
      id: '/_authenticated/app/admin/whatsapp'
      path: '/app/admin/whatsapp'
      fullPath: '/app/admin/whatsapp'
      preLoaderRoute: typeof AuthenticatedAppAdminWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/reviews': {
      id: '/_authenticated/app/admin/reviews'
      path: '/app/admin/reviews'
      fullPath: '/app/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAppAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/practitioners': {
      id: '/_authenticated/app/admin/practitioners'
      path: '/app/admin/practitioners'
      fullPath: '/app/admin/practitioners'
      preLoaderRoute: typeof AuthenticatedAppAdminPractitionersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/pharmacies': {
      id: '/_authenticated/app/admin/pharmacies'
      path: '/app/admin/pharmacies'
      fullPath: '/app/admin/pharmacies'
      preLoaderRoute: typeof AuthenticatedAppAdminPharmaciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/patients': {
      id: '/_authenticated/app/admin/patients'
      path: '/app/admin/patients'
      fullPath: '/app/admin/patients'
      preLoaderRoute: typeof AuthenticatedAppAdminPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/neighborhoods': {
      id: '/_authenticated/app/admin/neighborhoods'
      path: '/app/admin/neighborhoods'
      fullPath: '/app/admin/neighborhoods'
      preLoaderRoute: typeof AuthenticatedAppAdminNeighborhoodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/inventory': {
      id: '/_authenticated/app/admin/inventory'
      path: '/app/admin/inventory'
      fullPath: '/app/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAppAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/feedback': {
      id: '/_authenticated/app/admin/feedback'
      path: '/app/admin/feedback'
      fullPath: '/app/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAppAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/couriers': {
      id: '/_authenticated/app/admin/couriers'
      path: '/app/admin/couriers'
      fullPath: '/app/admin/couriers'
      preLoaderRoute: typeof AuthenticatedAppAdminCouriersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/appointments': {
      id: '/_authenticated/app/admin/appointments'
      path: '/app/admin/appointments'
      fullPath: '/app/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAppAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/reservations/$id/': {
      id: '/_authenticated/app/reservations/$id/'
      path: '/app/reservations/$id'
      fullPath: '/app/reservations/$id/'
      preLoaderRoute: typeof AuthenticatedAppReservationsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/prescriptions/$id/': {
      id: '/_authenticated/app/prescriptions/$id/'
      path: '/app/prescriptions/$id'
      fullPath: '/app/prescriptions/$id/'
      preLoaderRoute: typeof AuthenticatedAppPrescriptionsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/reservations/$id/track': {
      id: '/_authenticated/app/reservations/$id/track'
      path: '/app/reservations/$id/track'
      fullPath: '/app/reservations/$id/track'
      preLoaderRoute: typeof AuthenticatedAppReservationsIdTrackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/reservations/$id/checkout': {
      id: '/_authenticated/app/reservations/$id/checkout'
      path: '/app/reservations/$id/checkout'
      fullPath: '/app/reservations/$id/checkout'
      preLoaderRoute: typeof AuthenticatedAppReservationsIdCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/prescriptions/$id/pharmacies': {
      id: '/_authenticated/app/prescriptions/$id/pharmacies'
      path: '/app/prescriptions/$id/pharmacies'
      fullPath: '/app/prescriptions/$id/pharmacies'
      preLoaderRoute: typeof AuthenticatedAppPrescriptionsIdPharmaciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/praticien/rdv/$id': {
      id: '/_authenticated/app/praticien/rdv/$id'
      path: '/app/praticien/rdv/$id'
      fullPath: '/app/praticien/rdv/$id'
      preLoaderRoute: typeof AuthenticatedAppPraticienRdvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/pharmacy/$pharmacyId/reservations': {
      id: '/_authenticated/app/pharmacy/$pharmacyId/reservations'
      path: '/app/pharmacy/$pharmacyId/reservations'
      fullPath: '/app/pharmacy/$pharmacyId/reservations'
      preLoaderRoute: typeof AuthenticatedAppPharmacyPharmacyIdReservationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/pharmacy/$pharmacyId/inventory': {
      id: '/_authenticated/app/pharmacy/$pharmacyId/inventory'
      path: '/app/pharmacy/$pharmacyId/inventory'
      fullPath: '/app/pharmacy/$pharmacyId/inventory'
      preLoaderRoute: typeof AuthenticatedAppPharmacyPharmacyIdInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/courier/deliveries/$id': {
      id: '/_authenticated/app/courier/deliveries/$id'
      path: '/app/courier/deliveries/$id'
      fullPath: '/app/courier/deliveries/$id'
      preLoaderRoute: typeof AuthenticatedAppCourierDeliveriesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppOtcRoute: typeof AuthenticatedAppOtcRoute
  AuthenticatedAppScanRoute: typeof AuthenticatedAppScanRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAdminAppointmentsRoute: typeof AuthenticatedAppAdminAppointmentsRoute
  AuthenticatedAppAdminCouriersRoute: typeof AuthenticatedAppAdminCouriersRoute
  AuthenticatedAppAdminFeedbackRoute: typeof AuthenticatedAppAdminFeedbackRoute
  AuthenticatedAppAdminInventoryRoute: typeof AuthenticatedAppAdminInventoryRoute
  AuthenticatedAppAdminNeighborhoodsRoute: typeof AuthenticatedAppAdminNeighborhoodsRoute
  AuthenticatedAppAdminPatientsRoute: typeof AuthenticatedAppAdminPatientsRoute
  AuthenticatedAppAdminPharmaciesRoute: typeof AuthenticatedAppAdminPharmaciesRoute
  AuthenticatedAppAdminPractitionersRoute: typeof AuthenticatedAppAdminPractitionersRoute
  AuthenticatedAppAdminReviewsRoute: typeof AuthenticatedAppAdminReviewsRoute
  AuthenticatedAppAdminWhatsappRoute: typeof AuthenticatedAppAdminWhatsappRoute
  AuthenticatedAppCourierOnboardingRoute: typeof AuthenticatedAppCourierOnboardingRoute
  AuthenticatedAppPharmacyOnboardingRoute: typeof AuthenticatedAppPharmacyOnboardingRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
  AuthenticatedAppAppointmentsIndexRoute: typeof AuthenticatedAppAppointmentsIndexRoute
  AuthenticatedAppCourierIndexRoute: typeof AuthenticatedAppCourierIndexRoute
  AuthenticatedAppHealthIndexRoute: typeof AuthenticatedAppHealthIndexRoute
  AuthenticatedAppPharmacyIndexRoute: typeof AuthenticatedAppPharmacyIndexRoute
  AuthenticatedAppPraticienIndexRoute: typeof AuthenticatedAppPraticienIndexRoute
  AuthenticatedAppPrescriptionsIndexRoute: typeof AuthenticatedAppPrescriptionsIndexRoute
  AuthenticatedAppReservationsIndexRoute: typeof AuthenticatedAppReservationsIndexRoute
  AuthenticatedAppCourierDeliveriesIdRoute: typeof AuthenticatedAppCourierDeliveriesIdRoute
  AuthenticatedAppPharmacyPharmacyIdInventoryRoute: typeof AuthenticatedAppPharmacyPharmacyIdInventoryRoute
  AuthenticatedAppPharmacyPharmacyIdReservationsRoute: typeof AuthenticatedAppPharmacyPharmacyIdReservationsRoute
  AuthenticatedAppPraticienRdvIdRoute: typeof AuthenticatedAppPraticienRdvIdRoute
  AuthenticatedAppPrescriptionsIdPharmaciesRoute: typeof AuthenticatedAppPrescriptionsIdPharmaciesRoute
  AuthenticatedAppReservationsIdCheckoutRoute: typeof AuthenticatedAppReservationsIdCheckoutRoute
  AuthenticatedAppReservationsIdTrackRoute: typeof AuthenticatedAppReservationsIdTrackRoute
  AuthenticatedAppPrescriptionsIdIndexRoute: typeof AuthenticatedAppPrescriptionsIdIndexRoute
  AuthenticatedAppReservationsIdIndexRoute: typeof AuthenticatedAppReservationsIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppOtcRoute: AuthenticatedAppOtcRoute,
  AuthenticatedAppScanRoute: AuthenticatedAppScanRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAdminAppointmentsRoute:
    AuthenticatedAppAdminAppointmentsRoute,
  AuthenticatedAppAdminCouriersRoute: AuthenticatedAppAdminCouriersRoute,
  AuthenticatedAppAdminFeedbackRoute: AuthenticatedAppAdminFeedbackRoute,
  AuthenticatedAppAdminInventoryRoute: AuthenticatedAppAdminInventoryRoute,
  AuthenticatedAppAdminNeighborhoodsRoute:
    AuthenticatedAppAdminNeighborhoodsRoute,
  AuthenticatedAppAdminPatientsRoute: AuthenticatedAppAdminPatientsRoute,
  AuthenticatedAppAdminPharmaciesRoute: AuthenticatedAppAdminPharmaciesRoute,
  AuthenticatedAppAdminPractitionersRoute:
    AuthenticatedAppAdminPractitionersRoute,
  AuthenticatedAppAdminReviewsRoute: AuthenticatedAppAdminReviewsRoute,
  AuthenticatedAppAdminWhatsappRoute: AuthenticatedAppAdminWhatsappRoute,
  AuthenticatedAppCourierOnboardingRoute:
    AuthenticatedAppCourierOnboardingRoute,
  AuthenticatedAppPharmacyOnboardingRoute:
    AuthenticatedAppPharmacyOnboardingRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
  AuthenticatedAppAppointmentsIndexRoute:
    AuthenticatedAppAppointmentsIndexRoute,
  AuthenticatedAppCourierIndexRoute: AuthenticatedAppCourierIndexRoute,
  AuthenticatedAppHealthIndexRoute: AuthenticatedAppHealthIndexRoute,
  AuthenticatedAppPharmacyIndexRoute: AuthenticatedAppPharmacyIndexRoute,
  AuthenticatedAppPraticienIndexRoute: AuthenticatedAppPraticienIndexRoute,
  AuthenticatedAppPrescriptionsIndexRoute:
    AuthenticatedAppPrescriptionsIndexRoute,
  AuthenticatedAppReservationsIndexRoute:
    AuthenticatedAppReservationsIndexRoute,
  AuthenticatedAppCourierDeliveriesIdRoute:
    AuthenticatedAppCourierDeliveriesIdRoute,
  AuthenticatedAppPharmacyPharmacyIdInventoryRoute:
    AuthenticatedAppPharmacyPharmacyIdInventoryRoute,
  AuthenticatedAppPharmacyPharmacyIdReservationsRoute:
    AuthenticatedAppPharmacyPharmacyIdReservationsRoute,
  AuthenticatedAppPraticienRdvIdRoute: AuthenticatedAppPraticienRdvIdRoute,
  AuthenticatedAppPrescriptionsIdPharmaciesRoute:
    AuthenticatedAppPrescriptionsIdPharmaciesRoute,
  AuthenticatedAppReservationsIdCheckoutRoute:
    AuthenticatedAppReservationsIdCheckoutRoute,
  AuthenticatedAppReservationsIdTrackRoute:
    AuthenticatedAppReservationsIdTrackRoute,
  AuthenticatedAppPrescriptionsIdIndexRoute:
    AuthenticatedAppPrescriptionsIdIndexRoute,
  AuthenticatedAppReservationsIdIndexRoute:
    AuthenticatedAppReservationsIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  FeedbackRoute: FeedbackRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiRealtimeRoute: ApiRealtimeRoute,
  ApiStorageSplatRoute: ApiStorageSplatRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiAuthGoogleIndexRoute: ApiAuthGoogleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
